---
abstract: 'A storage class for Catalyst authentication from a class stored in Tangram'
author:
  - 'Tomas Doran, <bobtfish at bobtfish dot net>'
build_requires:
  Class::C3: 0
  DBD::SQLite: 0
  DBI: 0
  File::Temp: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Authentication-Store-Tangram
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Authentication: 0.10001
  Catalyst::Runtime: 5.70
  Class::Accessor::Fast: 0
  Tangram: 2.09
version: 0.002
